import numpy as np
import flwr as fl
from src.fl.server_clustering import perform_clustering

def _emit(message, logger=None):
    if logger:
        logger.info(message)
    else:
        print(message)

class BubbleServer:
    """
    Simulates the central server orchestrating PA-CFL.
    """
    def __init__(self, clients_dict):
        """
        clients_dict: dict of {client_id: FedStockClient instance}
        """
        self.clients = clients_dict
        self.bubbles = []
        self.isolated = []
        self.shared_global_weights = None
        self.shared_lstm_weights = None

    @staticmethod
    def _copy_parameters(parameters):
        return [param.copy() for param in parameters]

    @staticmethod
    def _fedavg(round_weights, round_samples):
        total_samples = sum(round_samples)
        aggregated_weights = []
        for layer_idx in range(len(round_weights[0])):
            layer_weighted_sum = sum(
                round_weights[c_idx][layer_idx] * (round_samples[c_idx] / total_samples)
                for c_idx in range(len(round_weights))
            )
            aggregated_weights.append(layer_weighted_sum)
        return aggregated_weights

    @staticmethod
    def _flatten_delta(local_weights, reference_weights):
        delta = np.concatenate(
            [
                (local - reference).reshape(-1)
                for local, reference in zip(local_weights, reference_weights)
            ]
        )
        return np.concatenate([np.maximum(delta, 0.0), np.maximum(-delta, 0.0)])

    def _cluster_update_vectors(self, update_vectors, max_clusters=15):
        client_ids = list(update_vectors.keys())
        vectors = np.array([update_vectors[cid] for cid in client_ids])
        labels, k_star, _, isolated = perform_clustering(
            vectors,
            max_clusters=max_clusters,
            complexity_penalty=0.001,
            singleton_penalty=0.05,
        )
        bubble_dict = {}
        for idx, label in enumerate(labels):
            bubble_dict.setdefault(int(label), []).append(client_ids[idx])
        return list(bubble_dict.values()), [client_ids[i] for i in isolated], int(k_star)

    def _build_shared_global_weights(self, global_warmup_rounds, epochs_per_round, logger=None):
        client_ids = list(self.clients.keys())
        if not client_ids:
            return None

        global_weights = self.clients[client_ids[0]].get_parameters({})
        _emit(
            f"[Shared Global] warmup_rounds={global_warmup_rounds}, clients={client_ids}",
            logger,
        )
        for warmup_round in range(1, global_warmup_rounds + 1):
            round_weights = []
            round_samples = []
            for cid in client_ids:
                updated_weights, num_samples, _ = self.clients[cid].fit(
                    parameters=global_weights,
                    config={"epochs": epochs_per_round},
                )
                round_weights.append(updated_weights)
                round_samples.append(num_samples)
            global_weights = self._fedavg(round_weights, round_samples)
            _emit(f"[Shared Global] warmup round {warmup_round}/{global_warmup_rounds} complete", logger)
        return self._copy_parameters(global_weights)
        
    def load_clustering_results(self, clustering_json_path, logger=None):
        """
        Loads pre-computed cluster assignments from JSON (generated by server_clustering.py).
        """
        import json
        _emit(f"Loading clustering results from {clustering_json_path}...", logger)
        with open(clustering_json_path, 'r') as f:
            data = json.load(f)
            
        assignments = data["assignments"]
        self.isolated = data["isolated_clients"]
        
        # Group into bubbles
        bubble_dict = {}
        for cid, cluster_id in assignments.items():
            if cid in self.isolated:
                continue
            if cluster_id not in bubble_dict:
                bubble_dict[cluster_id] = []
            bubble_dict[cluster_id].append(cid)
            
        self.bubbles = list(bubble_dict.values())
        _emit(f"Multi-Client Bubbles: {self.bubbles}", logger)
        _emit(f"Isolated (Single-Client) Bubbles: {self.isolated}", logger)
        
    def step_1_collect_and_cluster(self):
        """
        Collects noisy feature importances and performs agglomerative clustering.
        """
        print("--- PA-CFL Step 1 & 2: Feature Collection & Clustering ---")
        noisy_importances = []
        client_ids = list(self.clients.keys())
        
        for cid in client_ids:
            client = self.clients[cid]
            noisy_imp = client.extract_noisy_importance()
            noisy_importances.append(noisy_imp)
            
        # Save noisy feature importances to outputs folder
        import json
        import os
        import numpy as np
        
        importance_dict = {cid: imp.tolist() for cid, imp in zip(client_ids, noisy_importances)}
        os.makedirs("outputs", exist_ok=True)
        with open("outputs/feature_importances.json", 'w') as f:
            json.dump(importance_dict, f, indent=4)
        print("Feature importances saved to outputs/feature_importances.json")

        noisy_importances = np.array(noisy_importances)
        labels, k_star, _, _ = perform_clustering(
            noisy_importances,
            max_clusters=15,
            complexity_penalty=0.001,
            singleton_penalty=0.05,
        )
        
        print(f"Optimal Clusters (k*): {k_star}")
        
        # Group client IDs into bubbles
        bubble_groups = {}
        for idx, label in enumerate(labels):
            if label not in bubble_groups:
                bubble_groups[label] = []
            bubble_groups[label].append(client_ids[idx])
            
        # Separate into multi-client and single-client
        self.bubbles = []
        self.isolated = []
        for label, cids in bubble_groups.items():
            if len(cids) > 1:
                self.bubbles.append(cids)
            else:
                self.isolated.extend(cids)
                
        print(f"Multi-Client Bubbles: {self.bubbles}")
        print(f"Isolated (Single-Client) Bubbles: {self.isolated}")
        
        # Save clustering results to outputs folder
        self.save_clustering_results("outputs/clustering_results.json")

    def save_clustering_results(self, output_path):
        """
        Saves the current bubble and isolated client assignments to a JSON file.
        """
        import json
        import os
        
        assignments = {}
        for cluster_id, bubble in enumerate(self.bubbles):
            for cid in bubble:
                assignments[cid] = cluster_id
                
        # For isolated clients, use unique IDs starting after the last bubble ID
        start_id = len(self.bubbles)
        for i, cid in enumerate(self.isolated):
            assignments[cid] = start_id + i
            
        result = {
            "k_star": len(self.bubbles) + len(self.isolated),
            "assignments": assignments,
            "isolated_clients": self.isolated
        }
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w') as f:
            json.dump(result, f, indent=4)
        print(f"Clustering results saved to {output_path}")

    def step_3_federated_learning(
        self,
        num_rounds=3,
        epochs_per_round=5,
        logger=None,
        global_warmup_rounds=0,
        head_finetune_epochs=1,
        personalize_head=False,
        recluster_interval=10,
    ):
        """
        Performs FedAvg within each multi-client bubble.
        """
        _emit("\n--- PA-CFL Step 3: Federated Learning within Bubbles ---", logger)
        history = []
        self.shared_global_weights = self._build_shared_global_weights(
            global_warmup_rounds=global_warmup_rounds,
            epochs_per_round=epochs_per_round,
            logger=logger,
        )
        first_client = next(iter(self.clients.values()), None)
        self.shared_lstm_weights = (
            first_client.select_parameters(self.shared_global_weights, ("lstm.",))
            if personalize_head and first_client is not None
            else None
        )
        if personalize_head:
            return self._step_3_personalized_dynamic(
                num_rounds=num_rounds,
                epochs_per_round=epochs_per_round,
                head_finetune_epochs=head_finetune_epochs,
                recluster_interval=recluster_interval,
                logger=logger,
            )

        for b_idx, bubble_cids in enumerate(self.bubbles):
            _emit(f"\n[Bubble {b_idx}] Starting FL with clients: {bubble_cids}", logger)

            if personalize_head:
                # Every bubble shares the same LSTM backbone; each client keeps its own output head.
                global_weights = self._copy_parameters(self.shared_lstm_weights)
            else:
                global_weights = self._copy_parameters(self.shared_global_weights)

            for fl_round in range(1, num_rounds + 1):
                _emit(f"  Round {fl_round}/{num_rounds}", logger)
                
                # 1. Distribute global weights and Train locally
                round_weights = []
                round_samples = []
                
                for cid in bubble_cids:
                    client = self.clients[cid]
                    if personalize_head:
                        updated_weights, num_samples, _ = client.fit_shared_lstm(
                            parameters=global_weights,
                            config={"epochs": epochs_per_round}
                        )
                    else:
                        updated_weights, num_samples, _ = client.fit(
                            parameters=global_weights,
                            config={"epochs": epochs_per_round}
                        )
                    round_weights.append(updated_weights)
                    round_samples.append(num_samples)
                    
                # 2. Aggregate using FedAvg
                total_samples = sum(round_samples)
                global_weights = self._fedavg(round_weights, round_samples)
                
                # 3. Evaluate on clients
                total_rmse = 0.0
                total_smape = 0.0
                
                for cid in bubble_cids:
                    client = self.clients[cid]
                    if personalize_head:
                        _, _, metrics = client.evaluate_shared_lstm(parameters=global_weights, config={})
                    else:
                        _, _, metrics = client.evaluate(parameters=global_weights, config={})
                    total_rmse += metrics["rmse"] * round_samples[bubble_cids.index(cid)]
                    total_smape += metrics["smape"] * round_samples[bubble_cids.index(cid)]
                    
                avg_rmse = total_rmse / total_samples
                avg_smape = total_smape / total_samples
                
                metrics = {
                    "stage": "federated",
                    "bubble": b_idx,
                    "clients": bubble_cids,
                    "round": fl_round,
                    "num_samples": int(total_samples),
                    "rmse": float(avg_rmse),
                    "smape": float(avg_smape),
                }
                history.append(metrics)
                _emit(
                    f"    -> Bubble {b_idx} Global metrics: RMSE={avg_rmse:.4f}, SMAPE={avg_smape:.4f}",
                    logger,
                )

            if personalize_head and head_finetune_epochs > 0:
                for cid in bubble_cids:
                    client = self.clients[cid]
                    updated_weights, num_samples, _ = client.fit_head(
                        parameters=global_weights,
                        config={"epochs": head_finetune_epochs},
                    )
                    _, _, metrics = client.evaluate(parameters=updated_weights, config={})
                    history.append(
                        {
                            "stage": "head_finetune",
                            "bubble": b_idx,
                            "client": cid,
                            "epochs": head_finetune_epochs,
                            "num_samples": int(num_samples),
                            "rmse": metrics["rmse"],
                            "smape": metrics["smape"],
                        }
                    )
                    _emit(
                        f"    -> Client {cid} personalized head metrics: RMSE={metrics['rmse']:.4f}, SMAPE={metrics['smape']:.4f}",
                        logger,
                    )

        _emit("\nFL Training Complete.", logger)
        return history

    def _step_3_personalized_dynamic(
        self,
        num_rounds,
        epochs_per_round,
        head_finetune_epochs,
        recluster_interval,
        logger=None,
    ):
        history = []
        active_bubbles = [list(bubble) for bubble in self.bubbles] + [[cid] for cid in self.isolated]
        common_weights = {
            idx: self._copy_parameters(self.shared_lstm_weights)
            for idx in range(len(active_bubbles))
        }

        for fl_round in range(1, num_rounds + 1):
            _emit(f"  Personalized shared-LSTM round {fl_round}/{num_rounds}", logger)
            next_common_weights = {}
            latest_update_vectors = {}
            latest_client_weights = {}
            latest_client_samples = {}

            for b_idx, bubble_cids in enumerate(active_bubbles):
                global_weights = common_weights[b_idx]
                round_weights = []
                round_samples = []
                for cid in bubble_cids:
                    client = self.clients[cid]
                    updated_weights, num_samples, _ = client.fit_shared_lstm(
                        parameters=global_weights,
                        config={"epochs": epochs_per_round},
                    )
                    round_weights.append(updated_weights)
                    round_samples.append(num_samples)
                    latest_update_vectors[cid] = self._flatten_delta(updated_weights, global_weights)
                    latest_client_weights[cid] = updated_weights
                    latest_client_samples[cid] = num_samples

                aggregated_weights = self._fedavg(round_weights, round_samples)
                next_common_weights[b_idx] = aggregated_weights

                total_rmse = 0.0
                total_smape = 0.0
                total_samples = sum(round_samples)
                for cid, num_samples in zip(bubble_cids, round_samples):
                    _, _, metrics = self.clients[cid].evaluate_shared_lstm(
                        parameters=aggregated_weights,
                        config={},
                    )
                    total_rmse += metrics["rmse"] * num_samples
                    total_smape += metrics["smape"] * num_samples

                history.append(
                    {
                        "stage": "federated",
                        "bubble": b_idx,
                        "clients": bubble_cids,
                        "round": fl_round,
                        "num_samples": int(total_samples),
                        "rmse": float(total_rmse / total_samples),
                        "smape": float(total_smape / total_samples),
                    }
                )
                _emit(
                    f"    -> Bubble {b_idx} shared-LSTM metrics: RMSE={total_rmse / total_samples:.4f}, SMAPE={total_smape / total_samples:.4f}",
                    logger,
                )

            common_weights = next_common_weights
            should_recluster = (
                recluster_interval > 0
                and fl_round % recluster_interval == 0
                and fl_round < num_rounds
            )
            if should_recluster:
                active_bubbles, isolated, k_star = self._cluster_update_vectors(latest_update_vectors)
                global_weights = self._fedavg(
                    [latest_client_weights[cid] for cid in latest_client_weights],
                    [latest_client_samples[cid] for cid in latest_client_weights],
                )
                common_weights = {
                    idx: self._copy_parameters(global_weights)
                    for idx in range(len(active_bubbles))
                }
                self.bubbles = [bubble for bubble in active_bubbles if len(bubble) > 1]
                self.isolated = [cid for bubble in active_bubbles if len(bubble) == 1 for cid in bubble]
                self.shared_lstm_weights = self._copy_parameters(global_weights)
                _emit(
                    f"[Dynamic Recluster] round={fl_round}, k_star={k_star}, bubbles={active_bubbles}, isolated={isolated}",
                    logger,
                )
                self.save_clustering_results("outputs/clustering_results.json")


        if head_finetune_epochs > 0:
            for b_idx, bubble_cids in enumerate(active_bubbles):
                global_weights = common_weights[b_idx]
                for cid in bubble_cids:
                    client = self.clients[cid]
                    updated_weights, num_samples, _ = client.fit_head(
                        parameters=global_weights,
                        config={"epochs": head_finetune_epochs},
                    )
                    _, _, metrics = client.evaluate(parameters=updated_weights, config={})
                    history.append(
                        {
                            "stage": "head_finetune",
                            "bubble": b_idx,
                            "client": cid,
                            "epochs": head_finetune_epochs,
                            "num_samples": int(num_samples),
                            "rmse": metrics["rmse"],
                            "smape": metrics["smape"],
                        }
                    )
                    _emit(
                        f"    -> Client {cid} personalized head metrics: RMSE={metrics['rmse']:.4f}, SMAPE={metrics['smape']:.4f}",
                        logger,
                    )

        self.bubbles = [bubble for bubble in active_bubbles if len(bubble) > 1]
        self.isolated = []
        _emit("\nFL Training Complete.", logger)
        return history

    def step_4_personalized_learning(self, epochs=10, logger=None):
        """
        Performs local training only (Personalized FL) for isolated clients.
        """
        if not self.isolated:
            _emit("\nNo isolated clients to process.", logger)
            return []
            
        _emit("\n--- PA-CFL Step 4: Personalized Learning for Isolated Clients ---", logger)
        history = []
        for cid in self.isolated:
            if cid not in self.clients:
                continue
            _emit(f"\n[Personalized] Starting local training for client: {cid}", logger)
            client = self.clients[cid]
            
            # Start isolated bubbles from the same shared LSTM and fine-tune only the local head.
            if self.shared_lstm_weights is None:
                current_weights = client.get_parameters({})
                updated_weights, num_samples, _ = client.fit(
                    parameters=current_weights,
                    config={"epochs": epochs}
                )
                _, _, metrics = client.evaluate(parameters=updated_weights, config={})
            else:
                current_weights = self._copy_parameters(self.shared_lstm_weights)
                updated_weights, num_samples, _ = client.fit_head(
                    parameters=current_weights,
                    config={"epochs": epochs}
                )
                _, _, metrics = client.evaluate(parameters=updated_weights, config={})
            result = {
                "stage": "personalized",
                "client": cid,
                "epochs": epochs,
                "num_samples": int(num_samples),
                "rmse": metrics["rmse"],
                "smape": metrics["smape"],
            }
            history.append(result)
            _emit(
                f"    -> Client {cid} metrics after {epochs} epochs: RMSE={metrics['rmse']:.4f}, SMAPE={metrics['smape']:.4f}",
                logger,
            )

        return history
